### PR TITLE
Fix typos at hooks.asc

### PR DESCRIPTION
**Pull request by zettaittenani**
[8.3 Git のカスタマイズ - Git フック](https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA-Git-%E3%83%95%E3%83%83%E3%82%AF)のページにて、2点 typo と思われる箇所を見つけましたので、
修正させていただきたいです。

issue: https://github.com/progit/progit2-ja/issues/106

### CODE REVIEW

**Comment by tnir** [comment]
@harupong Could you take a look?

**Comment by okuryu** [comment]
@harupong doesn't have enough time to work on this project, so I'm talking to him to promote me to a maintainer for this project. I will merge this PR as soon as the permissions are updated.

**Comment by zettaittenani** [comment]
@okuryu 
I know you're very busy, but I’d be grateful if I could know the status.

>I'm talking to him to promote me to a maintainer for this project. I will merge this PR as soon as the permissions are updated.

**Review by kenjis — APPROVED** [review]

**Comment by zettaittenani** [comment]
@tnir @okuryu @kenjis
Hello, excuse me for mentioning multiple people.
Could you merge this approved PR? Or I'll close it in 10 days.
Thank you in advance.

**Comment by tnir** [comment]
@zettaittenani Thanks for reminding repo owners. I do not have `write` permission yet so consult @okuryu @kenjis to get this merged 😭

**Comment by tnir** [comment]
@jnavila Any comments on merging unmerged PRs like this? YOU ARE the only person who merged in the past two years 😁

**Comment by kenjis** [comment]
@zettaittenani I also don't have write permission.

**Comment by jnavila** [comment]
Who's ready to take the maintainership of this project?

**Comment by tnir** [comment]
@jnavila Thanks for merging. I would maintain the repo if you add me to the repo 😬

**Comment by zettaittenani** [comment]
Thank you guys so much for quick confirmation and decision!

**Comment by okuryu** [comment]
@jnavila Thanks for the merge. I will continue to maintain this repo in the future, but I am still waiting for @harupong to update the permissions.

**Pull request merged**
